/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'necromancer' at '8/16/14 1:56 AM' with Gradle 2.0
 *
 * @author necromancer, @date 8/16/14 1:56 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
